twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        ga_tracking: '%ga_tracking%'
        favicon: '%favicon%'
        cookiesaccepted_livetime: '%cookiesaccepted_livetime%'
        language_livetime: '%language_livetime%'
        captcha_website: '%captcha_website%'