1:
    name: header.icons.design.white
    css: design-white
2:
    name: header.icons.design.light
    css: design-light
3:
    name: header.icons.design.dark
    css: design-dark
4:
    name: header.icons.design.black
    css: design-black