impressum:
    name: "footer.impressum"
    href: "/information/impressum"
contact:
    name: "footer.contact"
    href: "/information/contact"
sponsors:
    name: "footer.sponsors"
    href: "/information/sponsors"
cookies:
    name: "footer.cookies"
    href: "/information/cookies"
conditions:
    name: "footer.conditions"
    href: "/information/conditions"
vhg:
    name: "footer.vhg"
    href: "https://www.valentin-heider-gymnasium.de/"