route_home:
    path: /
    controller: App\Controller\HomeController::index

route_videos_redirect_with_language:
    path: /videos/{class}
    controller: App\Controller\VideoController::redirect_with_language
    defaults:
        class: 5
    requirements:
        class: 1|2|3|4|5|6|7|8|9|12

route_videos_redirect_with_class:
    path: /videos/{language}
    controller: App\Controller\VideoController::redirect_with_class
    requirements:
        language: de|en

route_videos:
    path: /videos/{language}/{class}
    controller: App\Controller\VideoController::list
    requirements:
        class: 1|2|3|4|5|6|7|8|9|12
        language: de|en

route_video:
    path: /videos/{language}/{class}/{chapter}/{index}
    controller: App\Controller\VideoController::video
    requirements:
        class: 1|2|3|4|5|6|7|8|9|12
        language: de|en

route_account_login:
    path: /account/login
    controller: App\Controller\AccountController::login

route_account_register:
    path: /account/register
    controller: App\Controller\AccountController::register

route_account_logout:
    path: /account/logout
    methods: GET

route_account_me:
    path: /account/me
    controller: App\Controller\AccountController::me

route_account_action:
    path: /account/action
    controller: App\Controller\AccountController::action

route_account_verify:
    path: /account/verify
    controller: App\Controller\AccountController::verify

route_account_delete:
    path: /account/delete
    controller: App\Controller\AccountController::delete

route_account_request_password_reset:
    path: /account/requestpasswordreset
    controller: App\Controller\AccountController::request_password_reset

route_account_perform_password_reset:
    path: /account/performpasswordreset
    controller: App\Controller\AccountController::perform_password_reset

route_account_action_perform_password_reset:
    path: /account/actionperformpasswordreset
    controller: App\Controller\AccountController::action_perform_password_reset

route_account_user:
    path: /account/show/{id}
    controller: App\Controller\AccountController::user

route_account:
    path: /account
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: route_account_me
        permanent: true
        keepQueryParams: true

route_account_redirect_me:
    path: /me
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: route_account_me
        permanent: true
        keepQueryParams: true

route_account_redirect_login:
    path: /login
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: route_account_login
        permanent: true
        keepQueryParams: true

route_account_redirect_register:
    path: /register
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: route_account_register
        permanent: true
        keepQueryParams: true

route_account_redirect_logout:
    path: /logout
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: route_account_logout
        permanent: true
        keepQueryParams: true

route_admin:
    path: /admin
    controller: App\Controller\AdminController::index

route_admin_videoconfig:
    path: /admin/videoconfig
    controller: App\Controller\AdminController::videoconfig

route_admin_languageconfig:
    path: /admin/languageconfig
    controller: App\Controller\AdminController::languageconfig

route_admin_doaction:
    path: /admin/doaction
    controller: App\Controller\AdminController::doaction

route_information_contact:
    path: /information/contact
    controller: App\Controller\InformationController::contact

route_information_cookies:
    path: /information/cookies
    controller: App\Controller\InformationController::cookies

route_information_impressum:
    path: /information/impressum
    controller: App\Controller\InformationController::impressum

route_information_sponsors:
    path: /information/sponsors
    controller: App\Controller\InformationController::sponsors

router_information_conditions:
    path: /information/conditions
    controller: App\Controller\InformationController::conditions

route_information_redirect_contact:
    path: /contact
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: route_information_contact
        permanent: true
        keepQueryParams: true

route_information_redirect_cookies:
    path: /cookies
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: route_information_cookies
        permanent: true
        keepQueryParams: true

route_information_redirect_impressum:
    path: /impressum
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: route_information_impressum
        permanent: true
        keepQueryParams: true

route_information_redirect_sponsors:
    path: /sponsors
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: route_information_sponsors
        permanent: true
        keepQueryParams: true

route_information_redirect_conditions:
    path: /conditions
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: route_information_conditions
        permanent: true
        keepQueryParams: true

route_tools:
    path: /tools
    controller: App\Controller\ToolsController::tools

route_tools_calculator:
    path: /tools/calculator
    controller: App\Controller\ToolsController::calculator

route_tools_calculator_redirect:
    path: /calculator
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: route_tools_calculator
        permanent: true
        keepQueryParams: true

route_forum:
    path: /forum
    controller: App\Controller\ForumController::forum

route_forum_create: #Must be before route_forum_post
    path: /forum/create
    controller: App\Controller\ForumController::create

route_forum_post:
    path: /forum/{id}
    controller: App\Controller\ForumController::post