route_home:
  path: /
  controller: App\Controller\HomeController::index

route_videos_redirect_with_language:
  path: /videos/{class}
  controller: App\Controller\VideoController::redirect_with_language
  defaults:
    class: 5
  requirements:
    class: 1|2|3|4|5|6|7|8|9|12

route_videos_redirect_with_class:
  path: /videos/{language}
  controller: App\Controller\VideoController::redirect_with_class
  requirements:
    language: de|en

route_videos:
  path: /videos/{language}/{class}
  controller: App\Controller\VideoController::index
  requirements:
    class: 1|2|3|4|5|6|7|8|9|12
    language: de|en

route_account_redirect:
  path: /account
  controller: App\Controller\AccountController::redirect_me

route_account_redirect_login:
  path: /login
  controller: App\Controller\AccountController::redirect_login

route_account_redirect_register:
  path: /register
  controller: App\Controller\AccountController::redirect_register

route_account_redirect_logout:
  path: /logout
  controller: App\Controller\AccountController::redirect_logout

route_account_redirect_me:
  path: /me
  controller: App\Controller\AccountController::redirect_me

route_account_me:
  path: /account/me
  controller: App\Controller\AccountController::me

route_account_login:
  path: /account/login
  controller: App\Controller\AccountController::login

route_account_register:
  path: /account/register
  controller: App\Controller\AccountController::register

route_account_logout:
  path: /account/logout
  methods: GET