de:
    5:
        name: 5
        curriculum: https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/5/mathematik
        chapters:
            -   name: 1. Natürliche und ganze Zahlen - Addition und Subtraktion
                videos:
                    -   name: Natürliche und ganze Zahlen
                        source: de_5_1_1_1.mp4
                        thumbnail: ""

                    -   name: Stellenwert und Dezimalsystem
                        source: de_5_1_1_2.mp4
                        thumbnail: ""

                    -   name: Runden und Abschätzen
                        source: de_5_1_1_3.mp4
                        thumbnail: ""

                    -   name: Addition und Subtraktion ganzer Zahlen
                        source: de_5_1_2_1.mp4
                        thumbnail: ""

                    -   name: Addition und Subtraktion ganzer Zahlen (Version 2)
                        source: de_5_1_2_2.mp4
                        thumbnail: ""

                    -   name: Rechengesetzte Addition
                        source: de_5_1_2_3.mp4
                        thumbnail: ""

            -   name: 2. Geometrische Figuren und Lagebeziehungen
                videos: []

            -   name: 3. Natürliche und ganze Zahlen - Multiplikation und Division
                videos: []

            -   name: 4. Größen und Einheiten
                videos:
                    -   name: Fläche und Flächeninhalt
                        source: de_5_4_2_1.mp4
                        thumbnail: ""
                    
                    -   name: Oberflächeninhalt von Körpern
                        source: de_5_4_2_2.mp4
                        thumbnail: ""
                    
                    -   name: Flächeninhalt von Quadrat und Rechteck
                        source: de_5_4_2_3.mp4
                        thumbnail: ""
    6:
        name: 6
        curriculum: https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/6/mathematik
        chapters: []
    7:
        name: 7
        curriculum: https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/7/mathematik
        chapters: []
en: []