0:
    name: header.navigation.menu.settings.design.options.system
    css: system
1:
    name: header.navigation.menu.settings.design.options.white
    css: design-white
2:
    name: header.navigation.menu.settings.design.options.light
    css: design-light
3:
    name: header.navigation.menu.settings.design.options.dark
    css: design-dark
4:
    name: header.navigation.menu.settings.design.options.black
    css: design-black