system:
    localiced_name: header.navigation.menu.settings.design.options.system
    dark: false
white:
    localiced_name: header.navigation.menu.settings.design.options.white
    dark: false
light:
    localiced_name: header.navigation.menu.settings.design.options.light
    dark: false
dark:
    localiced_name: header.navigation.menu.settings.design.options.dark
    dark: true
black:
    localiced_name: header.navigation.menu.settings.design.options.black
    dark: false