de:
    5:
        name: 5
        curriculum: https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/5/mathematik
        chapters:
            -   name: 1. Natürliche und ganze Zahlen - Addition und Subtraktion
                videos:
                    -   name: Natürliche und ganze Zahlen
                        source: de_5_1_1.mp4
                        thumbnail: de_5_1_1.png

                    -   name: Stellenwert und Dezimalsystem
                        source: de_5_1_2.mp4
                        thumbnail: de_5_1_2.png

                    -   name: Runden und Abschätzen
                        source: de_5_1_3.mp4
                        thumbnail: de_5_1_3.png

                    -   name: Addition und Subtraktion ganzer Zahlen
                        source: de_5_1_4.mp4
                        thumbnail: de_5_1_4.png

                    -   name: Addition und Subtraktion ganzer Zahlen (Version 2)
                        source: de_5_1_5.mp4
                        thumbnail: de_5_1_5.png

                    -   name: Rechengesetzte Addition
                        source: de_5_1_6.mp4
                        thumbnail: de_5_1_6.png

            -   name: 2. Geometrische Figuren und Lagebeziehungen
                videos: []

            -   name: 3. Natürliche und ganze Zahlen - Multiplikation und Division
                videos:
                    -   name: Multiplikation ganzer Zahlen
                        source: de_5_3_1.mp4
                        thumbnail: ""

                    -   name: Division ganzer Zahlen
                        source: de_5_3_2.mp4
                        thumbnail: ""
                    
                    -   name: Verbindung der Grundrechenarten bei ganzen Zahlen
                        source: de_5_3_3_3.mp4
                        thumbnail: ""

            -   name: 4. Größen und Einheiten
                videos:
                    -   name: Fläche und Flächeninhalt
                        source: de_5_4_1.mp4
                        thumbnail: de_5_4_1.png
                    
                    -   name: Oberflächeninhalt von Körpern
                        source: de_5_4_2.mp4
                        thumbnail: de_5_4_2.png
                    
                    -   name: Flächeninhalt von Quadrat und Rechteck
                        source: de_5_4_3.mp4
                        thumbnail: de_5_4_3.png
                    
                    -   name: Größe und ihre Einheit
                        source: de_5_4_4.mp4
                        thumbnail: ""
    6:
        name: 6
        curriculum: https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/6/mathematik
        chapters:
            -   name: Bruchtteile und Bruchzahlen
                videos:
                    -   name: Einführung Brüche und Kreisdiagramme
                        source: de_6_1_1.mp4
                        thumbnail: ""

                    -   name: Bruchteile und Anteile
                        source: de_6_1_2.mp4
                        thumbnail: ""
                    
                    -   name: Erweitern und Kürzen
                        source: de_6_1_3.mp4
                        thumbnail: ""
                    
                    -   name: Addition und Subtraktion von Brüchen
                        source: de_6_1_4.mp4
                        thumbnail: ""
    7:
        name: 7
        curriculum: https://www.lehrplanplus.bayern.de/fachlehrplan/gymnasium/7/mathematik
        chapters:
            -   name: Aufstellen und Interpretieren von Termen
                videos:
                    -   name: Aufstellen und Interpretieren von Termen
                        source: de_7_1_1.mp4
                        thumbnail: ""
en: []